sudo: false
notifications:
  hipchat:
    rooms:
      secure: LW5XPoH6eOe/VPAVg1vOUk0jvWm662w8R30Wna0ZtcE2ZV40EHmyJfY7PLDA3/o/wme0vHhZh+cKWjbHbhF7RFrYAkNl6RLgmRkvMhaI/UKpztWRfIuopiJg2snHT0bH3nODm/2l9iSyhBc39lpxARFAhsUoN6j5zLyLyqfA7Xg=
    template:
    - '<a href="%{build_url}">%{repository}#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a>
      : %{author}): %{message}'
    format: html
    notify: true
  slack:
    secure: MG3wEGLelQgasOVa5SyNbIfGWpvsmKZPF9moTrbLSrDgMptMxThSIDfVuAHvpBGsOw9o+izbTD26sbt1OQE9A9ipJfxUxZ+/LmYvaG0rSWvYEX9dIw9qp84pFyqwuO7nZlReeM7Ye9A2hYTBCZjqUsg8pwUlUUv065X3Qhp2IbY=
addons:
  sauce_connect: false
language: node_js
node_js:
- 0.10
- 0.12
- iojs-v1.2
# env:
# - TEST_SUITE=unit
# - TEST_SUITE=e2e
# - TEST_SUITE=lint
matrix:
  # exclude:
  # - node_js: 0.10
  #   env: TEST_SUITE=e2e
  # - node_js: iojs-v1.2
  #   env: TEST_SUITE=e2e
  # - node_js: 0.10
  #   env: TEST_SUITE=lint
  # - node_js: iojs-v1.2
  #   env: TEST_SUITE=lint
  include:
  - node_js: 0.10
    env: TEST_SUITE=unit
  - node_js: 0.12
    env: TEST_SUITE=unit
  - node_js: iojs-v1.2
    env: TEST_SUITE=unit
  - node_js: 0.12
    env: TEST_SUITE=e2e
    addons:
      sauce_connect: true
  - node_js: 0.12
    env: TEST_SUITE=lint
  fast_finish: true
cache:
  directories:
  - node_modules
install:
- npm install -g gulp
- npm install
before_script:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
#- sleep 3
- test/pre_test.sh
script:
- test/test.sh
after_script:
- gulp send-stats-to-coveralls
before_deploy:
- gulp release --version-suffix=${TRAVIS_TAG:-$TRAVIS_COMMIT}
deploy:
- provider: releases
  api_key:
    secure: Txqa+XwZOOdAaxRckHGXSCkT7GEUh4R6R0MtTu8otA1Vv2/W5qTICuFnaEzV/FVWrSzYbMwM+mAFHQ1L8SXOnAvbSFwnjaOjIvaEUESItkSITDXncTJItJatzMUXT0SjRTm4Jy6LQ0Pq0qXxfWD6DzsWxPVPsthprb+aEzS0/m8=
  file: build/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: ushahidi/platform-client
    node: 0.12
    tags: true
    all_branches: true
