sudo: false
notifications:
  hipchat:
    rooms:
      secure: LW5XPoH6eOe/VPAVg1vOUk0jvWm662w8R30Wna0ZtcE2ZV40EHmyJfY7PLDA3/o/wme0vHhZh+cKWjbHbhF7RFrYAkNl6RLgmRkvMhaI/UKpztWRfIuopiJg2snHT0bH3nODm/2l9iSyhBc39lpxARFAhsUoN6j5zLyLyqfA7Xg=
    template:
    - '<a href="%{build_url}">%{repository}#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a>
      : %{author}): %{message}'
    format: html
    notify: true
  slack:
    secure: MG3wEGLelQgasOVa5SyNbIfGWpvsmKZPF9moTrbLSrDgMptMxThSIDfVuAHvpBGsOw9o+izbTD26sbt1OQE9A9ipJfxUxZ+/LmYvaG0rSWvYEX9dIw9qp84pFyqwuO7nZlReeM7Ye9A2hYTBCZjqUsg8pwUlUUv065X3Qhp2IbY=
language: node_js
env:
  global:
  - SELENIUM_HOST=hub.browserstack.com
  - SELENIUM_PORT=80
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis $TRAVIS_REPO_SLUG Job \#$TRAVIS_JOB_NUMBER"
  - secure: "LQmO6Htm9B61Dv8+L5mjMZr5AGxVbhMIxxPhnVvNulp8yBdnTA+syigZ0P2hIFGdK27z8wXKZCtEitKyBxJcQ3HhVxpTlrEC/0I5OEm7nS47bqQTDFRyCt38PaHvp4YLKIIkdWsvZoyIUnjHuQLd+N7kh64orfy002YHzhliH+I="
  - secure: "KY4B6oQBL0tQbikOiXMLvJmjPvMOjThlDsiBOM6G2TM5tlgMgD/bKhZTWbxUkto1nj/fOwXwwsZvAHRO8SvXhYLX7BtCig/nldBmEozn6vDPaKLTTWZe1Ky4cRwJxF9pRUANAA/AmIxLFMrpt9nKYGPkOXjJd2nds3uFzdR2b/U="
matrix:
  include:
  # Run everything with v5 (match production)
  - node_js: 5
    env: TEST_SUITE=e2e PROTRACTOR_SUITE=full
  - node_js: 5
    env: TEST_SUITE=e2e PROTRACTOR_SUITE=post_views
  - node_js: 5
    env: TEST_SUITE=e2e PROTRACTOR_SUITE=settings
  - node_js: 5
    env: TEST_SUITE=lint
  - node_js: 5
    env: TEST_SUITE=unit
  # Run unit test with 0.12 and current stable too
  - node_js: 0.12
    env: TEST_SUITE=unit
  - node_js: stable
    env: TEST_SUITE=unit
  fast_finish: true
cache:
  directories:
  - node_modules
install:
- npm install -g gulp
- npm install
before_script:
- test/pre_test.sh
script:
- test/test.sh
after_script:
- gulp send-stats-to-coveralls
before_deploy:
- gulp release --version-suffix=${TRAVIS_TAG:-$TRAVIS_COMMIT}
deploy:
- provider: releases
  api_key:
    secure: Txqa+XwZOOdAaxRckHGXSCkT7GEUh4R6R0MtTu8otA1Vv2/W5qTICuFnaEzV/FVWrSzYbMwM+mAFHQ1L8SXOnAvbSFwnjaOjIvaEUESItkSITDXncTJItJatzMUXT0SjRTm4Jy6LQ0Pq0qXxfWD6DzsWxPVPsthprb+aEzS0/m8=
  file: build/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: ushahidi/platform-client
    node: 0.12
    tags: true
    all_branches: true
