notifications:
  hipchat:
    rooms:
      secure: LW5XPoH6eOe/VPAVg1vOUk0jvWm662w8R30Wna0ZtcE2ZV40EHmyJfY7PLDA3/o/wme0vHhZh+cKWjbHbhF7RFrYAkNl6RLgmRkvMhaI/UKpztWRfIuopiJg2snHT0bH3nODm/2l9iSyhBc39lpxARFAhsUoN6j5zLyLyqfA7Xg=
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.10
- 0.12
- iojs-v1.2
install:
- npm install -g gulp
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- gulp build --angular-mock-backend
- gulp node-server &
- sleep 3
script:
- gulp test
- npm run protractor
after_script:
- gulp send-stats-to-coveralls
before_deploy:
- gulp release --version-suffix=${TRAVIS_TAG:-$TRAVIS_COMMIT}
deploy:
  - provider: heroku
    api_key:
      secure: XeBcMSubQ+kDtk7B93iJy5HCvXTxp708hUtn9RfjKtNjOyTOha25xZ3lRnYqrhgAOlTY7kieu8QtI4KOZmiRy3U1NwIardvUU44I4f9Q4DDJRGGrPyd61WZwyuAiPWUrePGadZJW2kSuxRXyD3QNm8mBr2njcQp9ln9TpS/57S4=
    app:
      master: ushahidi-platform-master
      release: ushahidi-platform-release
    on:
      repo: ushahidi/platform-client
      node: 0.12
      branch:
        - master
        - release
  - provider: releases
    api_key:
      secure: Txqa+XwZOOdAaxRckHGXSCkT7GEUh4R6R0MtTu8otA1Vv2/W5qTICuFnaEzV/FVWrSzYbMwM+mAFHQ1L8SXOnAvbSFwnjaOjIvaEUESItkSITDXncTJItJatzMUXT0SjRTm4Jy6LQ0Pq0qXxfWD6DzsWxPVPsthprb+aEzS0/m8=
    file: build/*
    file_glob: true
    skip_cleanup: true
    on:
      repo: ushahidi/platform-client
      node: 0.12
      tags: true
      all_branches: true

